import {
  FaRobot,
  FaBrain,
  FaCode,
  FaGraduationCap,
  FaUsers,
  FaMicrosoft,
  FaCertificate,
  FaTrophy,
  FaProjectDiagram,
  FaNetworkWired,
  FaLanguage,
  FaCloud,
  FaDatabase,
  FaEye,
  FaChartLine,
  FaAtom,
  FaUsersCog,
  FaSearchPlus,
  FaCogs,
  FaChartBar,
  FaGlobe,
  FaTools,
  FaUniversity,
  FaSchool,
  FaAward,
  FaExternalLinkAlt,
  FaLinkedinIn,
  FaGithub,
  FaEnvelope,
  FaRocket,
  FaPaperPlane,
  FaMapMarkerAlt,
  FaDownload,
  FaUserAstronaut,
  FaLayerGroup,
  FaFlask,
  FaBriefcase,
  FaSalesforce,
} from "react-icons/fa";
import { SiLeetcode } from "react-icons/si";

const map = {
  robot: FaRobot,
  brain: FaBrain,
  code: FaCode,
  gradcap: FaGraduationCap,
  users: FaUsers,
  microsoft: FaMicrosoft,
  certificate: FaCertificate,
  trophy: FaTrophy,
  diagram: FaProjectDiagram,
  network: FaNetworkWired,
  language: FaLanguage,
  cloud: FaCloud,
  database: FaDatabase,
  eye: FaEye,
  chart: FaChartLine,
  atom: FaAtom,
  "users-cog": FaUsersCog,
  search: FaSearchPlus,
  cogs: FaCogs,
  "chart-bar": FaChartBar,
  globe: FaGlobe,
  tools: FaTools,
  university: FaUniversity,
  school: FaSchool,
  award: FaAward,
  external: FaExternalLinkAlt,
  linkedin: FaLinkedinIn,
  github: FaGithub,
  leetcode: SiLeetcode,
  salesforce: FaSalesforce,
  envelope: FaEnvelope,
  rocket: FaRocket,
  paperplane: FaPaperPlane,
  pin: FaMapMarkerAlt,
  download: FaDownload,
  astronaut: FaUserAstronaut,
  layers: FaLayerGroup,
  flask: FaFlask,
  briefcase: FaBriefcase,
  nptel: FaUniversity,
};

export default function Icon({ name, className = "" }) {
  const Cmp = map[name] || FaRobot;
  return <Cmp className={className} />;
}
